# Minimal Makefile to build only os05a20 sensor driver as an external module
# (Temporarily excluding imx708 due to API differences with kernel 6.1)

obj-m += os05a20.o

# If you later need imx708, add:
# obj-m += imx708.o
